### ISSUE TITLE
how to set admin role?

### ISSUE THREAD

**Issue by kleutzinger** [hswolff/votey-uppy#15]
I've got the app deployed successfully, but I can't find a way to set admin role for my account on my instance. Thanks!

![image](https://user-images.githubusercontent.com/6435727/107024825-62138d00-675d-11eb-916d-ef282cde5909.png)

**Comment by hswolff** [comment]
Ah! Good point! Let me update the docs to show this. Will do so tonight.

**Comment by hswolff** [comment]
Basically on the `users` collection you have to run the following for the user you want to be the admin:

```
db.users.update(   { _id: ObjectId('600c75000307d1df954899e3') },  {role: 'admin' } );
```

**Comment by hswolff** [comment]
Fixed via https://github.com/hswolff/votey-uppy/commit/7cc7c23127f5c57a9cffd37293db2b61ca970cce
